spring:
  application:
    name: e-journal-gateway
  cloud:
    gateway:
      routes:
        - id: E-JOURNAL-AUTH
          uri: lb://e-journal-auth
          predicates:
            - Path=/api/v1/auth/**
        - id: E-JOURNAL-BACK
          uri: lb://e-journal-back
          predicates:
            - Path=/api/v1/journal/**
      discovery:
        locator:
          enabled: true

server:
  port: 8080
  ssl:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG