spring:
  application:
    name: e-journal-gateway
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      routes:
        - id: e-journal-auth
          uri: lb://e-journal-auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /${segment}

        - id: e-journal-back
          uri: lb://e-journal-back
          predicates:
            - Path=/api/v1/journal/**
          filters:
            - RewritePath=/api/v1/journal/(?<segment>.*), /${segment}

        - id: spa_route
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - SetPath=/index.html
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080
  ssl:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true