spring:
  application:
    name: e-journal-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
  main:
    web-application-type: reactive
server:
  port: 8080
  ssl:
    enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG